### ISSUE TITLE
automodule :undoc-members: does not include undocumented module constants

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1063]
The only way of getting undocumented constants defined in the module into the documentation seems to be to explicitly define:

```
   .. py:data:: SOMECONST
```

It would be less surprising if :undoc-members: option to automodule sucked in undocumented constants as well.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1063
- Originally reported by: Daniel Svensson
- Originally created at: 2012-12-18T22:32:14.449

**Comment by tk0miya** [comment]
Certainly, module global variables not having docstring is not documented even if `:undoc-members:`.

**Comment by jsmedmar** [comment]
Wow, this issue was created in 2012. Are there any plans of making sure undocumented constants make it to the doc when using `:undoc-members:
`?

**Comment by tk0miya** [comment]
While six years, nobody had not tried to fix this. How about you? PR is always welcome :-)

**Comment by jsmedmar** [comment]
haha! guess no one has been lazy enough to complain about having to doc their constants

**Comment by jsmedmar** [comment]
Ok @tk0miya, see #5387.

**Comment by jsmedmar** [comment]
@tk0miya, do you know how I could differentiate from objects defined in the module between those imported? That was the roadblock I hit whilst implementing a solution for this ticket in #5387.

**Comment by tk0miya** [comment]
AFAIK, there are no way to investigate it. All classes and functions have `__module__` attribute indicates where the object defined. But instances does not have it.
I guess our pycode module (`sphinx.pycode`) help it.

I'll take a look after releasing 1.8.0.

Thank you for your help.

**Comment by rmorshea** [comment]
You can work around this by adding your constants to `__all__`. This is tedious though.

**Comment by tk0miya** [comment]
Fixed by #6423 .
Thank you for reporting.

**Comment by tk0miya** [comment]
Reopened now. Because #6423 causes some troubles. I'll try this again in future version.

**Comment by goekce** [comment]
> You can work around this by adding your constants to `__all__`. This is tedious though.

Did not work for me. I am using `sphinx-build` 3.41 with `conf.py`:

```
...
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
}
```
I included some module-level variables in `__all__`, but only the variables which have `#: comment` were picked up :-/

**Comment by con-f-use** [comment]
https://github.com/sphinx-doc/sphinx/pull/6423 doesn't seem to have fixed this or we have a regression.

**Comment by vivodi** [comment]
It's been 13 years, and this issue still exists. I always thought it was my misconfiguration until I found this issue.
